const Config = {
  HOLES_COUNT: 8,
  MOLE_INTERVAL_IN_MS: 1000,
  MOLE_LIFE_TIME_IN_MS: 700,
  GAME_DURATION_IN_SEC: 30,
  UPDATE_DIFFICULTY_INTERVAL_IN_SECS: 5,
  MIN_MOLE_LIFE_IN_MS: 600,
}

export default Config
